# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
# Enables Gradle Build Cache.
org.gradle.caching=true
# Enables Gradle Configuration Cache, the preferred Gradle execution mode.
org.gradle.configuration-cache=true
# Build independent subprojects in parallel.
org.gradle.parallel=true

# AndroidX package structure.
android.useAndroidX=true

# Kotlin code style for this project: "official" or "obsolete".
kotlin.code.style=official

# Namespace each library's R class so it only contains its own resources.
android.nonTransitiveRClass=true
